name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.6.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^5.0.0
  image_picker: ^0.5.0
  quill_delta: ^1.0.0-dev.1.0
  meta: ^1.1.0
  notus:
    git:
      url: git://github.com/joshmatta/zefyr.git
      ref: 69f30336f48e090d245752eddecc1acd7d2c630a
      path: packages/notus

dev_dependencies:
  flutter_test:
    sdk: flutter
